from fastapi.testclient import TestClient

from app.config import get_settings
from app.main import app
from app.models import Role
from app.services.token_service import issue_signup_token

# 1x1 PNG
PNG_BYTES = bytes.fromhex(
    "89504E470D0A1A0A0000000D49484452000000010000000108060000001F15C4890000000D49444154789C636018050000080001B20A2DB40000000049454E44AE426082"
)


def _signup(client: TestClient, username: str, token: str | None = None) -> dict:
    payload = {"username": username}
    if token:
        payload["token"] = token

    begin = client.post("/api/auth/signup/begin", json=payload)
    assert begin.status_code == 200

    complete = client.post(
        "/api/auth/signup/complete",
        json={
            "challenge_id": begin.json()["challenge_id"],
            "credential": {
                "id": f"cred-{username}-1",
                "response": {"attestationObject": f"pk-{username}-1"},
            },
        },
    )
    assert complete.status_code == 200
    return complete.json()


def _bootstrap_superadmin_token(test_session_factory) -> str:
    settings = get_settings()
    with test_session_factory() as db:
        _, token = issue_signup_token(
            db,
            role=Role.SUPERADMIN,
            created_by_id=None,
            expires_in_minutes=60,
            token_pepper=settings.token_pepper,
        )
        db.commit()
        return token


def test_user_can_open_assigned_questionnaire_and_submit_response(test_session_factory) -> None:
    bootstrap_token = _bootstrap_superadmin_token(test_session_factory)

    with TestClient(app) as super_client:
        _signup(super_client, "root", token=bootstrap_token)

        created = super_client.post(
            "/api/admin/questionnaires",
            json={
                "title": "OCT Reader",
                "description": "Evaluation",
                "instructions_markdown": "Pick the AI-generated image.",
            },
        )
        assert created.status_code == 200
        questionnaire_id = created.json()["id"]
        version_id = created.json()["latest_version_id"]
        assert version_id

        uploaded = super_client.post(
            "/api/admin/assets/upload",
            data={"questionnaire_id": questionnaire_id},
            files=[("files", ("Task1/1a.png", PNG_BYTES, "image/png"))],
        )
        assert uploaded.status_code == 200
        asset_id = uploaded.json()[0]["id"]

        question = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/questions",
            json={
                "position": 1,
                "prompt_text": "Which image was generated by AI?",
                "question_type": "single_choice",
                "is_required": True,
                "config": {"stimulus_asset_ids": [asset_id]},
                "choices": [
                    {"position": 1, "label": "a", "value": "a"},
                    {"position": 2, "label": "b", "value": "b"},
                    {"position": 3, "label": "c", "value": "c"},
                ],
            },
        )
        assert question.status_code == 200
        question_id = question.json()["id"]

        published = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/publish"
        )
        assert published.status_code == 200

        user_token = super_client.post(
            "/api/admin/signup-tokens",
            json={
                "role": "user",
                "expires_in_minutes": 60,
                "questionnaire_version_ids": [version_id],
            },
        )
        assert user_token.status_code == 200

    with TestClient(app) as user_client:
        _signup(user_client, "alice", token=user_token.json()["token"])

        assigned = user_client.get("/api/user/assigned-questionnaires")
        assert assigned.status_code == 200
        assigned_items = assigned.json()
        assert len(assigned_items) == 1
        assert assigned_items[0]["questionnaire_version_id"] == version_id
        assert assigned_items[0]["submitted_at"] is None

        detail = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail.status_code == 200
        detail_json = detail.json()
        assert detail_json["title"] == "OCT Reader"
        assert len(detail_json["questions"]) == 1
        assert detail_json["existing_answers"] == []

        answer_page_before_consent = user_client.get(f"/answer/{version_id}", follow_redirects=False)
        assert answer_page_before_consent.status_code == 303
        assert answer_page_before_consent.headers["location"] == f"/answer/{version_id}/consent"

        consent_page = user_client.get(f"/answer/{version_id}/consent")
        assert consent_page.status_code == 200

        consent_status_before = user_client.get(f"/api/user/questionnaires/{version_id}/consent")
        assert consent_status_before.status_code == 200
        assert consent_status_before.json()["consented"] is False

        missing_required = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={"answers": []},
        )
        assert missing_required.status_code == 403

        consent_submit = user_client.post(
            f"/api/user/questionnaires/{version_id}/consent",
            json={"consented": True},
        )
        assert consent_submit.status_code == 200
        assert consent_submit.json()["consented"] is True

        answer_page_after_consent = user_client.get(f"/answer/{version_id}?q=1")
        assert answer_page_after_consent.status_code == 200

        missing_required_after_consent = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={"answers": []},
        )
        assert missing_required_after_consent.status_code == 400

        submitted = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": "b",
                    }
                ]
            },
        )
        assert submitted.status_code == 200

        detail_after = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail_after.status_code == 200
        existing_answers = detail_after.json()["existing_answers"]
        assert len(existing_answers) == 1
        assert existing_answers[0]["question_id"] == question_id
        assert existing_answers[0]["value"] == "b"

        assigned_after = user_client.get("/api/user/assigned-questionnaires")
        assert assigned_after.status_code == 200
        assert assigned_after.json()[0]["submitted_at"] is not None

        asset_content = user_client.get(
            f"/api/user/questionnaires/{version_id}/assets/{asset_id}/content"
        )
        assert asset_content.status_code == 200
        assert asset_content.headers["content-type"].startswith("image/png")
        assert asset_content.content == PNG_BYTES
