from fastapi.testclient import TestClient

from app.config import get_settings
from app.main import app
from app.models import Role
from app.services.consent_service import DEFAULT_CONSENT_TEXT
from app.services.token_service import issue_signup_token

# 1x1 PNG
PNG_BYTES = bytes.fromhex(
    "89504E470D0A1A0A0000000D49484452000000010000000108060000001F15C4890000000D49444154789C636018050000080001B20A2DB40000000049454E44AE426082"
)


def _signup(client: TestClient, username: str, token: str | None = None) -> dict:
    payload = {"username": username}
    if token:
        payload["token"] = token

    begin = client.post("/api/auth/signup/begin", json=payload)
    assert begin.status_code == 200

    complete = client.post(
        "/api/auth/signup/complete",
        json={
            "challenge_id": begin.json()["challenge_id"],
            "credential": {
                "id": f"cred-{username}-1",
                "response": {"attestationObject": f"pk-{username}-1"},
            },
        },
    )
    assert complete.status_code == 200
    return complete.json()


def _login(client: TestClient, username: str) -> dict:
    begin = client.post("/api/auth/login/begin", json={"username": username})
    assert begin.status_code == 200

    complete = client.post(
        "/api/auth/login/complete",
        json={
            "challenge_id": begin.json()["challenge_id"],
            "credential": {"id": f"cred-{username}-1"},
        },
    )
    assert complete.status_code == 200
    return complete.json()


def _bootstrap_superadmin_token(test_session_factory) -> str:
    settings = get_settings()
    with test_session_factory() as db:
        _, token = issue_signup_token(
            db,
            role=Role.SUPERADMIN,
            created_by_id=None,
            expires_in_minutes=60,
            token_pepper=settings.token_pepper,
        )
        db.commit()
        return token


def _complete_profile(client: TestClient, username: str, yoe: int = 1) -> None:
    updated = client.patch(
        "/api/auth/me",
        json={"username": username, "year_of_experience": yoe},
    )
    assert updated.status_code == 200
    assert updated.json()["year_of_experience"] == yoe


def test_user_can_open_assigned_questionnaire_and_submit_response(test_session_factory) -> None:
    bootstrap_token = _bootstrap_superadmin_token(test_session_factory)

    with TestClient(app) as super_client:
        _signup(super_client, "root", token=bootstrap_token)

        created = super_client.post(
            "/api/admin/questionnaires",
            json={
                "title": "OCT Reader",
                "description": "Evaluation",
                "instructions_markdown": "Pick the AI-generated image.",
            },
        )
        assert created.status_code == 200
        questionnaire_id = created.json()["id"]
        version_id = created.json()["latest_version_id"]
        assert version_id

        uploaded = super_client.post(
            "/api/admin/assets/upload",
            data={"questionnaire_id": questionnaire_id},
            files=[("files", ("Task1/1a.png", PNG_BYTES, "image/png"))],
        )
        assert uploaded.status_code == 200
        asset_id = uploaded.json()[0]["id"]

        question = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/questions",
            json={
                "position": 1,
                "prompt_text": "Which image was generated by AI?",
                "question_type": "single_choice",
                "is_required": True,
                "config": {"stimulus_asset_ids": [asset_id]},
                "choices": [
                    {"position": 1, "label": "a", "value": "a"},
                    {"position": 2, "label": "b", "value": "b"},
                    {"position": 3, "label": "c", "value": "c"},
                ],
            },
        )
        assert question.status_code == 200
        question_id = question.json()["id"]

        published = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/publish"
        )
        assert published.status_code == 200

        user_token = super_client.post(
            "/api/admin/signup-tokens",
            json={
                "role": "user",
                "expires_in_minutes": 60,
                "questionnaire_version_ids": [version_id],
            },
        )
        assert user_token.status_code == 200

    with TestClient(app) as user_client:
        _signup(user_client, "alice", token=user_token.json()["token"])
        _complete_profile(user_client, "alice", yoe=5)

        assigned = user_client.get("/api/user/assigned-questionnaires")
        assert assigned.status_code == 200
        assigned_items = assigned.json()
        assert len(assigned_items) == 1
        assert assigned_items[0]["questionnaire_version_id"] == version_id
        assert assigned_items[0]["submitted_at"] is None

        detail = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail.status_code == 200
        detail_json = detail.json()
        assert detail_json["title"] == "OCT Reader"
        assert detail_json["consent_text"] == DEFAULT_CONSENT_TEXT
        assert len(detail_json["questions"]) == 1
        assert detail_json["existing_answers"] == []

        answer_page_before_consent = user_client.get(f"/answer/{version_id}", follow_redirects=False)
        assert answer_page_before_consent.status_code == 303
        assert answer_page_before_consent.headers["location"] == f"/answer/{version_id}/consent"

        consent_page = user_client.get(f"/answer/{version_id}/consent")
        assert consent_page.status_code == 200

        consent_status_before = user_client.get(f"/api/user/questionnaires/{version_id}/consent")
        assert consent_status_before.status_code == 200
        assert consent_status_before.json()["consented"] is False

        missing_required = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={"answers": []},
        )
        assert missing_required.status_code == 403

        draft_before_consent = user_client.post(
            f"/api/user/questionnaires/{version_id}/draft",
            json={"answers": [{"question_id": question_id, "value": "a"}]},
        )
        assert draft_before_consent.status_code == 403

        consent_submit = user_client.post(
            f"/api/user/questionnaires/{version_id}/consent",
            json={"consented": True},
        )
        assert consent_submit.status_code == 200
        assert consent_submit.json()["consented"] is True

        answer_page_after_consent = user_client.get(f"/answer/{version_id}?q=1")
        assert answer_page_after_consent.status_code == 200

        missing_required_after_consent = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={"answers": []},
        )
        assert missing_required_after_consent.status_code == 400

        draft_saved = user_client.post(
            f"/api/user/questionnaires/{version_id}/draft",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": "a",
                    }
                ]
            },
        )
        assert draft_saved.status_code == 200
        assert draft_saved.json()["answer_count"] == 1

        detail_with_draft = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail_with_draft.status_code == 200
        existing_answers_before_submit = detail_with_draft.json()["existing_answers"]
        assert len(existing_answers_before_submit) == 1
        assert existing_answers_before_submit[0]["question_id"] == question_id
        assert existing_answers_before_submit[0]["value"] == "a"

        assigned_mid = user_client.get("/api/user/assigned-questionnaires")
        assert assigned_mid.status_code == 200
        assert assigned_mid.json()[0]["submitted_at"] is None

        submitted = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": "b",
                    }
                ]
            },
        )
        assert submitted.status_code == 200

        detail_after = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail_after.status_code == 200
        existing_answers = detail_after.json()["existing_answers"]
        assert len(existing_answers) == 1
        assert existing_answers[0]["question_id"] == question_id
        assert existing_answers[0]["value"] == "b"

        assigned_after = user_client.get("/api/user/assigned-questionnaires")
        assert assigned_after.status_code == 200
        assert assigned_after.json()[0]["submitted_at"] is not None

        asset_content = user_client.get(
            f"/api/user/questionnaires/{version_id}/assets/{asset_id}/content"
        )
        assert asset_content.status_code == 200
        assert asset_content.headers["content-type"].startswith("image/png")
        assert asset_content.content == PNG_BYTES


def test_server_saved_draft_survives_new_session(test_session_factory) -> None:
    bootstrap_token = _bootstrap_superadmin_token(test_session_factory)

    with TestClient(app) as super_client:
        _signup(super_client, "root", token=bootstrap_token)

        created = super_client.post(
            "/api/admin/questionnaires",
            json={
                "title": "Draft persistence questionnaire",
                "description": "Draft persistence check",
                "instructions_markdown": "Type your notes.",
            },
        )
        assert created.status_code == 200
        questionnaire_id = created.json()["id"]
        version_id = created.json()["latest_version_id"]
        assert version_id

        question = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/questions",
            json={
                "position": 1,
                "prompt_text": "Notes",
                "question_type": "short_text",
                "is_required": True,
                "config": {},
                "choices": [],
            },
        )
        assert question.status_code == 200
        question_id = question.json()["id"]

        published = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/publish"
        )
        assert published.status_code == 200

        user_token = super_client.post(
            "/api/admin/signup-tokens",
            json={
                "role": "user",
                "expires_in_minutes": 60,
                "questionnaire_version_ids": [version_id],
            },
        )
        assert user_token.status_code == 200

    with TestClient(app) as first_user_client:
        _signup(first_user_client, "alice", token=user_token.json()["token"])
        _complete_profile(first_user_client, "alice", yoe=4)

        consent_submit = first_user_client.post(
            f"/api/user/questionnaires/{version_id}/consent",
            json={"consented": True},
        )
        assert consent_submit.status_code == 200

        saved_draft = first_user_client.post(
            f"/api/user/questionnaires/{version_id}/draft",
            json={"answers": [{"question_id": question_id, "value": "draft-from-session-one"}]},
        )
        assert saved_draft.status_code == 200
        assert saved_draft.json()["answer_count"] == 1

    with TestClient(app) as second_user_client:
        _login(second_user_client, "alice")

        detail = second_user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail.status_code == 200
        existing_answers = detail.json()["existing_answers"]
        assert len(existing_answers) == 1
        assert existing_answers[0]["question_id"] == question_id
        assert existing_answers[0]["value"] == "draft-from-session-one"


def test_user_receives_custom_questionnaire_consent_text(test_session_factory) -> None:
    bootstrap_token = _bootstrap_superadmin_token(test_session_factory)
    custom_consent = "Custom consent for this questionnaire."

    with TestClient(app) as super_client:
        _signup(super_client, "root", token=bootstrap_token)

        created = super_client.post(
            "/api/admin/questionnaires",
            json={
                "title": "Custom Consent Questionnaire",
                "description": "Evaluation",
                "consent_text": custom_consent,
                "instructions_markdown": "Read and answer.",
            },
        )
        assert created.status_code == 200
        questionnaire_id = created.json()["id"]
        version_id = created.json()["latest_version_id"]
        assert version_id

        published = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/publish"
        )
        assert published.status_code == 200

        user_token = super_client.post(
            "/api/admin/signup-tokens",
            json={
                "role": "user",
                "expires_in_minutes": 60,
                "questionnaire_version_ids": [version_id],
            },
        )
        assert user_token.status_code == 200

    with TestClient(app) as user_client:
        _signup(user_client, "alice", token=user_token.json()["token"])

        detail = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail.status_code == 200
        assert detail.json()["consent_text"] == custom_consent


def test_user_can_submit_labeled_points_annotation(test_session_factory) -> None:
    bootstrap_token = _bootstrap_superadmin_token(test_session_factory)

    with TestClient(app) as super_client:
        _signup(super_client, "root", token=bootstrap_token)

        created = super_client.post(
            "/api/admin/questionnaires",
            json={
                "title": "Point annotation",
                "description": "Annotation flow",
                "instructions_markdown": "Annotate lesions.",
            },
        )
        assert created.status_code == 200
        questionnaire_id = created.json()["id"]
        version_id = created.json()["latest_version_id"]
        assert version_id

        uploaded = super_client.post(
            "/api/admin/assets/upload",
            data={"questionnaire_id": questionnaire_id},
            files=[("files", ("annotate/OCT/1.png", PNG_BYTES, "image/png"))],
        )
        assert uploaded.status_code == 200
        asset_id = uploaded.json()[0]["id"]

        question = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/questions",
            json={
                "position": 1,
                "prompt_text": "Mark drusen points.",
                "question_type": "annotation",
                "is_required": True,
                "config": {
                    "case_key": "case-0001",
                    "recipe_type": "labeled_points",
                    "stimulus_asset_ids": [asset_id],
                },
                "choices": [
                    {"position": 1, "label": "Drusen (DS)", "value": "DS"},
                    {"position": 2, "label": "Microaneurysms (MA)", "value": "MA"},
                ],
            },
        )
        assert question.status_code == 200
        question_id = question.json()["id"]

        published = super_client.post(
            f"/api/admin/questionnaires/{questionnaire_id}/versions/{version_id}/publish"
        )
        assert published.status_code == 200

        user_token = super_client.post(
            "/api/admin/signup-tokens",
            json={
                "role": "user",
                "expires_in_minutes": 60,
                "questionnaire_version_ids": [version_id],
            },
        )
        assert user_token.status_code == 200

    with TestClient(app) as user_client:
        _signup(user_client, "annotator", token=user_token.json()["token"])
        _complete_profile(user_client, "annotator", yoe=3)

        consent_submit = user_client.post(
            f"/api/user/questionnaires/{version_id}/consent",
            json={"consented": True},
        )
        assert consent_submit.status_code == 200

        required_empty = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": {"points": []},
                    }
                ]
            },
        )
        assert required_empty.status_code == 400
        assert "Required annotation is empty" in required_empty.json()["detail"]

        invalid_label = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": {
                            "points": [
                                {"label": "NOT_ALLOWED", "x": 120, "y": 88},
                            ]
                        },
                    }
                ]
            },
        )
        assert invalid_label.status_code == 400
        assert "is not allowed" in invalid_label.json()["detail"]

        submitted = user_client.post(
            f"/api/user/questionnaires/{version_id}/responses",
            json={
                "answers": [
                    {
                        "question_id": question_id,
                        "value": {
                            "points": [
                                {"label": "DS", "x": 120, "y": 88},
                                {"label": "Microaneurysms (MA)", "x": 200.5, "y": 101.25},
                            ]
                        },
                    }
                ]
            },
        )
        assert submitted.status_code == 200

        detail_after = user_client.get(f"/api/user/questionnaires/{version_id}")
        assert detail_after.status_code == 200
        existing_answers = detail_after.json()["existing_answers"]
        assert len(existing_answers) == 1
        assert existing_answers[0]["question_id"] == question_id
        assert existing_answers[0]["value"] == {
            "points": [
                {"label": "DS", "x": 120, "y": 88},
                {"label": "MA", "x": 200.5, "y": 101.25},
            ]
        }
